### ISSUE TITLE
Java EE 6 servlet annotations

### ISSUE THREAD

**Issue by CrystalMethod** [buschmais/jqa-javaee6-plugin#4]
I've noticed, that JEE6 annotations are not yet supported by JQA. So I started to write some concepts based on Cypher queries. `com.buschmais.jqassistant.plugin.javaee6.impl.scanner.WebXmlScannerPlugin` does a lot more than just adding labels. But the results of `XXXScannerPlugin`and Cypher-based concepts should be as identical as possible. What is the preferred way of doing this? Are there some hints?

**Comment by StephanPirnbaum** [comment]
To be continued in https://github.com/jqassistant-plugin/jqassistant-jee-plugin/issues/1
